// <auto-generated />
using Intravision.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Intravision.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907131525_AddDrinksAndCoins")]
    partial class AddDrinksAndCoins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Intravision.Models.Entities.Coin", b =>
                {
                    b.Property<int>("Denomination")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Denomination");

                    b.ToTable("Coins", null, t =>
                        {
                            t.HasCheckConstraint("CK_Coins_Denomination", "[Denomination] IN (1, 2, 5, 10)");

                            t.HasCheckConstraint("CK_Coins_Quantity", "[Quantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Denomination = 1,
                            IsBlocked = false,
                            Quantity = 0
                        },
                        new
                        {
                            Denomination = 2,
                            IsBlocked = false,
                            Quantity = 0
                        },
                        new
                        {
                            Denomination = 5,
                            IsBlocked = false,
                            Quantity = 0
                        },
                        new
                        {
                            Denomination = 10,
                            IsBlocked = false,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("Intravision.Models.Entities.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Drinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Drinks_ImagePath", "LEN(LTRIM(RTRIM([ImagePath]))) > 0");

                            t.HasCheckConstraint("CK_Drinks_Name", "LEN(LTRIM(RTRIM([Name]))) > 0");

                            t.HasCheckConstraint("CK_Drinks_Price", "[Price] > 0");

                            t.HasCheckConstraint("CK_Drinks_Quantity", "[Quantity] >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
